name: XeonSuitePortal
version: ${project.version}.b${build.number}
description: Portalplugin
authors: [Kekshaus]
main: de.nlinz.xeonSuite.portal.Portalplugin
load: POSTWORLD
depend: [XeonSuiteBukkit]

commands:
  setportal:
    description: Set your home.
  delportal:
    description: Teleport back to your set home.

permissions:
    xeonSuite.portal.team:
        description: Alle Permissions
        children:
            xeonSuite.portal.setportal: true
            xeonSuite.portal.delportal: true
    xeonSuite.portal.setportal:
        description: Teleport to home
        default: op
    xeonSuite.portal.delportal:
        description: Teleport to home
        default: op