name: MineSuitePortal
version: ${project.version}
description: PortalPlugin
authors: [Kekshaus]
main: de.linzn.mineSuite.portal.PortalPlugin
load: POSTWORLD
depend: [MineSuiteCore]

commands:
  setportal:
    description: Set new portal.
  unsetportal:
    description: Remove a exist portal.

permissions:
    mineSuite.portal.team:
        description: Alle Permissions
        children:
            mineSuite.portal.setportal: true
            mineSuite.portal.delportal: true
    mineSuite.portal.setportal:
        description: Set a new portal
        default: op
    mineSuite.portal.delportal:
        description: Delete a new portal
        default: op