name: XeonSuitePortal
version: ${project.version}
description: Portalplugin
authors: [Kekshaus]
main: de.nlinz.xeonSuite.portal.Portalplugin
load: POSTWORLD
depend: [XeonSuiteBukkit]

commands:
  setportal:
    description: Set new portal.
  delportal:
    description: Remove a exist portal.

permissions:
    xeonSuite.portal.team:
        description: Alle Permissions
        children:
            xeonSuite.portal.setportal: true
            xeonSuite.portal.delportal: true
    xeonSuite.portal.setportal:
        description: Set a new portal
        default: op
    xeonSuite.portal.delportal:
        description: Delete a new portal
        default: op